#!/bin/bash

#SBATCH --job-name=install_env
#SBATCH --time=24:00:00  # Adjust as needed
#SBATCH --mem=32G         # Adjust as needed
#SBATCH --cpus-per-task=16
#SBATCH --gpus=1
#SBATCH -p gpu          # Adjust partition as needed
#SBATCH --output=/home/gplanella/repos/QGNN/jobs/job_outputs/install_env_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Navigate to the script directory
cd $HOME/repos/QGNN

conda env create -f environment_qgnn_gpu.yml